/*
*   LMMS Project Packager
*   Copyright © 2022 Luxon Jean-Pierre
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef XML_HPP_INCLUDED
#define XML_HPP_INCLUDED

#include "../external/tinyxml2/tinyxml2.h"

#include <vector>
#include <string>
#include <memory>
#include <algorithm>
#include <unordered_map>

namespace xml
{

/**
    Structure of a valid LMMS project file:

    ```
    <?xml version="1.0"?>
    <!DOCTYPE lmms-project>
    <lmms-project creator="LMMS" version="1.0" creatorversion="1.2.2" type="song">
        <!-- Some data -->
        ...
        <!-- Some data -->
    </lmms-project>
    ```
    A valid project is a song project generated by a supported version of LMMS.
*/
bool checkLMMSProjectBuffer( const std::unique_ptr<char []>& buffer, const unsigned int bufsize );
bool projectInfo( const std::unique_ptr<char []>& buffer, const unsigned int bufsize );

// Export

const std::vector<std::string> retrieveResourcesFromXmlFile( const std::string& xml_file );
void configureExportedXmlFile( const std::string& project_file, const std::unordered_map<std::string, std::string>& resources );

// Import

void configureImportedProject( const std::string& project_file, const std::vector<std::string>& resources );

// Misc

template<typename T>
const std::vector<T *> getAllElementsByNames( const tinyxml2::XMLElement * root, const std::vector<std::string>& names );

}

#include "xml.tpp"

#endif // XML_HPP_INCLUDED
